// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"butter/app"
	"butter/middleware"
	"butter/pkg/user/controller"
	"butter/pkg/user/repository"
	"butter/pkg/user/service"
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializedServer() *fiber.App {
	userRepository := repository.NewUserRepositoryImpl()
	userService := service.NewUserServiceImpl(userRepository)
	db := app.NewDb()
	userController := controller.NewUserControllerImpl(userService, db)
	fiberHandlerSet := app.FiberHandlerSet{
		UserController: userController,
	}
	authMiddleware := middleware.NewAuthMiddleware(userService, db)
	fiberApp := app.NewFiber(fiberHandlerSet, authMiddleware)
	return fiberApp
}

// injector.go:

var ProvideFiber = wire.NewSet(app.NewFiber, wire.Struct(new(app.FiberHandlerSet), "*"))
